var INCR_RECT = 10;
var INCR_DIAG = 7;
var SHOOT_INCR_RECT = 20;
var SHOOT_INCR_DIAG = 14;

var TIMER_INT = 40;
var SHOOT_DIV = 3;

var TANK_W2 = 16;
var TANK_H2 = 21;
var TANK_R = 21;
var TANK_DIAG = parseInt(Math.round(Math.sqrt(2)/2*TANK_H2));
var ARENA_WIDTH = 1600;
var ARENA_HEIGHT = 1200;
var BOARD_WIDTH = 640;
var BOARD_HEIGHT = 480;
var BASE_WIDTH = 120;
var BASE_HEIGHT = 120;
var BASE_ENTRANCE = 60;

var HEALTH_BOT_OFFS = 35;
var HEALTH_WIDTH = 10;
var ENERGY_BOT_OFFS = 20;
var ENERGY_WIDTH = 10;
var SCORE_T_OFFS = 20;

var DIRT_W = 10;
var DIRT_H = 10;
var DIRT_X_CNT = ARENA_WIDTH / DIRT_W;
var DIRT_Y_CNT = ARENA_HEIGHT / DIRT_H;


var MAX_HEALTH = 100;
var BULLET_DAMAGE = 5;
var HEALTH_INC = 1;

var MAX_ENERGY = 100;
var BULLET_ENERGY = 2;
var ENERGY_INC = 2;
