"use strict";

var Consts = {
    INCR_RECT: 10,
    INCR_DIAG: 7,
    SHOOT_INCR_RECT: 20,
    SHOOT_INCR_DIAG: 14,

    TIMER_INT: 40,
    SHOOT_DIV: 3,

    TANK_W2: 16,
    TANK_H2: 21,
    TANK_R: 21,
    ARENA_WIDTH: 1600,
    ARENA_HEIGHT: 1200,
    BOARD_WIDTH: 640,
    BOARD_HEIGHT: 480,
    BASE_WIDTH: 120,
    BASE_HEIGHT: 120,
    BASE_ENTRANCE: 60,

    HEALTH_BOT_OFFS: 35,
    HEALTH_WIDTH: 10,
    ENERGY_BOT_OFFS: 20,
    ENERGY_WIDTH: 10,
    SCORE_T_OFFS: 20,

    DIRT_W: 20,
    DIRT_H: 20,

    MAX_HEALTH: 100,
//BULLET_DAMAGE: 5,
//HEALTH_INC: 1,

    MAX_ENERGY: 100,
    BULLET_ENERGY: 1
//ENERGY_INC: 2
};

Consts.TANK_DIAG = parseInt(Math.round(Math.sqrt(2) / 2 * Consts.TANK_H2));
Consts.DIRT_X_CNT = Consts.ARENA_WIDTH / Consts.DIRT_W;
Consts.DIRT_Y_CNT = Consts.ARENA_HEIGHT / Consts.DIRT_H;
